from fastapi import APIRouter
from pydantic import BaseModel
from typing import Literal

router = APIRouter()


# ── Request & Response shapes ─────────────────────────────────
class ExplainRequest(BaseModel):
    concept: str                                             # e.g. "Thermodynamics second law"
    course: str                                              # e.g. "ENSA Physics S3"
    level: Literal["beginner", "intermediate", "advanced"] = "intermediate"


class VideoResult(BaseModel):
    title: str
    url: str
    channel: str


class ExplainResponse(BaseModel):
    concept: str
    explanation: str
    videos: list[VideoResult]


# ── Endpoint ──────────────────────────────────────────────────
@router.post("/concept", response_model=ExplainResponse)
def explain_concept(req: ExplainRequest):
    """
    Receives a concept + student level.
    Returns a simplified explanation + 3-5 YouTube videos.

    SPRINT 1: Returns mock data.
    SPRINT 2: Replace with LangChain (Gemini Flash) + YouTube Data API.
    """

    # MOCK RESPONSE — replace entirely in Sprint 2
    return ExplainResponse(
        concept=req.concept,
        explanation=(
            f"[MOCK] Simplified explanation of '{req.concept}' "
            f"for a {req.level} student in {req.course}. "
            "This will be generated by Gemini Flash in Sprint 2."
        ),
        videos=[
            VideoResult(
                title=f"[MOCK] {req.concept} — Full Explanation",
                url="https://youtube.com/watch?v=PLACEHOLDER_1",
                channel="MockEduChannel",
            ),
            VideoResult(
                title=f"[MOCK] {req.concept} — Practice Problems",
                url="https://youtube.com/watch?v=PLACEHOLDER_2",
                channel="MockEduChannel",
            ),
        ],
    )
